[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
specs = "0.14"
specs-derive = "0.4"
[dependencies.sdl2]
sdl2 = "*"
defalut-features = false
features = ["image"]
